application: thoughtsapp-1141
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: thoughts.API
- url: /cron/.*
  script: thoughts.CRON
  login: admin

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: 2.5.2